# Generated by Django 3.0.5 on 2020-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='controller_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.IntegerField(max_length=15)),
                ('image', models.ImageField(upload_to='backend_site/controller_user')),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
