# Generated by Django 3.0.8 on 2020-09-21 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='controller_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='backend_site/controller_user')),
                ('password', models.CharField(max_length=15)),
                ('user_type', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='suspect_person_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('gender', models.CharField(default='unknown', max_length=100)),
                ('cnic', models.BigIntegerField(default=0)),
                ('address', models.CharField(default='unknown', max_length=300)),
                ('education', models.CharField(default='unknown', max_length=300)),
                ('marital_status', models.CharField(default='unknown', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(default='2050-01-01')),
                ('nationalilty', models.CharField(default='unknown', max_length=100)),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 22, 53, 58, 706367))),
                ('status', models.BooleanField(default=0)),
                ('description', models.CharField(default='unknown', max_length=2000)),
                ('image', models.ImageField(upload_to='backend_site/suspect_image')),
                ('image_array', models.CharField(default='unknown', max_length=9000)),
            ],
        ),
    ]
