# Generated by Django 3.0.8 on 2020-09-21 18:22

import backend_site.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 23, 22, 33, 743357)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='image',
            field=models.ImageField(upload_to=backend_site.models.upload_location),
        ),
    ]
