# Generated by Django 3.0.5 on 2020-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller_user',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='controller_user',
            name='user_type',
            field=models.BooleanField(default=0),
        ),
    ]
