# Generated by Django 3.0.5 on 2020-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0002_auto_20200417_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller_user',
            name='cnic',
            field=models.IntegerField(),
        ),
    ]
