# Generated by Django 3.1.2 on 2020-12-06 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0002_auto_20200921_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect_person_detail',
            name='image_array',
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 17, 17, 38, 305207)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
