# Generated by Django 3.1.2 on 2020-12-17 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0003_auto_20201206_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('gender', models.CharField(default='unknown', max_length=100)),
                ('cnic', models.BigIntegerField(default=0)),
                ('address', models.CharField(default='unknown', max_length=300)),
                ('date_of_birth', models.DateField(default='2050-01-01')),
                ('phone_number', models.BigIntegerField(default=0)),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2020, 12, 17, 19, 57, 44, 527906))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 19, 57, 44, 526994)),
        ),
    ]
