# Generated by Django 3.0.5 on 2020-04-26 18:31

import backend_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0004_auto_20200417_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='suspect_person_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('gender', models.CharField(default='unknown', max_length=100)),
                ('cnic', models.BigIntegerField(default=0)),
                ('address', models.CharField(default='unknown', max_length=300)),
                ('education', models.CharField(default='unknown', max_length=300)),
                ('marital_status', models.CharField(default='unknown', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(default=None)),
                ('nationalilty', models.CharField(default='unknown', max_length=100)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=0)),
                ('image', models.ImageField(upload_to=backend_site.models.upload_location)),
            ],
        ),
    ]
