# Generated by Django 3.1.2 on 2020-12-17 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0005_auto_20201217_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='password',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 21, 6, 4, 178221)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 21, 6, 4, 178888)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 21, 6, 4, 177131)),
        ),
    ]
