# Generated by Django 3.0.3 on 2020-07-24 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0006_auto_20200426_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 3, 11, 56, 922579)),
        ),
    ]
