# Generated by Django 3.0.8 on 2020-07-29 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0007_auto_20200724_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 19, 50, 468728)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='image',
            field=models.ImageField(upload_to='suspect_img'),
        ),
    ]
