# Generated by Django 3.0.8 on 2020-07-29 16:52

import backend_site.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0008_auto_20200729_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 52, 19, 629652)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='image',
            field=models.ImageField(upload_to=backend_site.models.upload_location),
        ),
    ]
