# Generated by Django 3.1.2 on 2020-12-18 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0008_auto_20201218_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='suspect_from_anonymous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('description', models.CharField(default='unknown', max_length=600)),
                ('report_date', models.DateTimeField(default=datetime.datetime(2020, 12, 18, 16, 4, 33, 164644))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='suspect_from_app_user',
            name='description',
            field=models.CharField(default='unknown', max_length=600),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 16, 4, 33, 162484)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 16, 4, 33, 163648)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 16, 4, 33, 160979)),
        ),
    ]
