# Generated by Django 3.1.2 on 2020-12-26 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0011_auto_20201218_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 55, 14, 205518)),
        ),
        migrations.AlterField(
            model_name='suspect_from_anonymous',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 55, 14, 206799)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 55, 14, 206180)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 16, 55, 14, 204547)),
        ),
        migrations.CreateModel(
            name='caught_suspect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('suspect_image', models.ImageField(upload_to='caught_suspect')),
                ('suspect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_site.suspect_person_detail')),
            ],
        ),
    ]
