# Generated by Django 3.1.2 on 2020-12-27 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0017_auto_20201227_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 961934)),
        ),
        migrations.AlterField(
            model_name='caught_suspect',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 964165)),
        ),
        migrations.AlterField(
            model_name='suspect_from_anonymous',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 963495)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 962763)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 960716)),
        ),
        migrations.CreateModel(
            name='suspect_track_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date_time', models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 965015))),
                ('recent_track_date_time', models.DateTimeField(default=datetime.datetime(2020, 12, 27, 17, 39, 38, 965048))),
                ('status', models.IntegerField(default=0)),
                ('suspect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_site.suspect_person_detail')),
            ],
        ),
    ]
