# Generated by Django 3.1.2 on 2020-12-27 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0018_auto_20201227_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 613257)),
        ),
        migrations.AlterField(
            model_name='caught_suspect',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 615679)),
        ),
        migrations.AlterField(
            model_name='caught_suspect',
            name='suspect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_site.suspect_track_list'),
        ),
        migrations.AlterField(
            model_name='suspect_from_anonymous',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 614490)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 613901)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 612308)),
        ),
        migrations.AlterField(
            model_name='suspect_track_list',
            name='recent_track_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 614996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suspect_track_list',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 18, 43, 11, 614964, tzinfo=utc)),
        ),
    ]
