# Generated by Django 3.1.5 on 2021-02-07 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0020_auto_20210124_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 82747)),
        ),
        migrations.AlterField(
            model_name='caught_suspect',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 85381)),
        ),
        migrations.AlterField(
            model_name='suspect_from_anonymous',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 84273)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 83391)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 81826)),
        ),
        migrations.AlterField(
            model_name='suspect_track_list',
            name='recent_track_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 84801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suspect_track_list',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 46, 5, 84761, tzinfo=utc)),
        ),
    ]
