# Generated by Django 3.1.5 on 2021-02-08 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_site', '0021_auto_20210207_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 87634)),
        ),
        migrations.AlterField(
            model_name='caught_suspect',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 90104)),
        ),
        migrations.AlterField(
            model_name='suspect_from_anonymous',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 88991)),
        ),
        migrations.AlterField(
            model_name='suspect_from_app_user',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 88264)),
        ),
        migrations.AlterField(
            model_name='suspect_person_detail',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 86720)),
        ),
        migrations.AlterField(
            model_name='suspect_track_list',
            name='recent_track_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 89532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suspect_track_list',
            name='report_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 14, 33, 16, 89493, tzinfo=utc)),
        ),
    ]
